# Site settings

title: Annual Report
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: pkp
github_username:  pkp

# Build settings

plugins:
  - jekyll-feed

sass:
    style: compressed
exclude: ["README.md"]
markdown: kramdown
