# Site settings

title: PKP’s Annual Report 2020
description: >- # this means to ignore newlines until "baseurl:"
  PKP is a multi-university initiative developing (free) open source software and conducting research to improve the quality and reach of scholarly publishing.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
collections:
  - sections

# Authors
author:
  name: Public Knowledge Project
  abbr: PKP
  github: pkp
  twitter: pkp

# Build settings
plugins:
  - jekyll-target-blank

sass:
    style: compressed
exclude: ["README.md"]
markdown: kramdown

target-blank:
  noreferrer: false
